default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fmw_development
  username: fmw
  password: <%= ENV['FMW_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: fmw_test
  username: fmw
  password: <%= ENV['FMW_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: fmw_production
  username: fmw
  password: <%= ENV['FMW_DATABASE_PASSWORD'] %>
