seed_words = [
  { text: 'Alice', count: 2 },
  { text: 'was', count: 1 },
  { text: 'beginning', count: 3 },
  { text: 'to', count: 1 },
  { text: 'get', count: 1 },
  { text: 'very', count: 2 },
  { text: 'tired', count: 1 },
  { text: 'of', count: 1 },
  { text: 'sitting', count: 2 },
  { text: 'by', count: 1 },
  { text: 'her', count: 1 },
  { text: 'sister', count: 2 },
  { text: 'on', count: 1 },
  { text: 'the', count: 1 },
  { text: 'bank', count: 1 },
  { text: 'Alice', count: 2 },
  { text: 'was', count: 1 },
  { text: 'beginning', count: 3 },
  { text: 'to', count: 1 },
  { text: 'get', count: 1 },
  { text: 'very', count: 2 },
  { text: 'tired', count: 1 },
  { text: 'of', count: 1 },
  { text: 'sitting', count: 2 },
  { text: 'by', count: 1 },
  { text: 'her', count: 1 },
  { text: 'sister', count: 2 },
  { text: 'on', count: 1 },
  { text: 'the', count: 1 },
  { text: 'bank', count: 1 }
]

seed_words.each {|word| Word.create(word)}
